Distributed
caracal-pipeline/crystalball pull request #72
Opened 2024-12-18 08:07 UTC by AlecThomson

- [x] Tests added / passed

Downstream from #70. Closes #71.

- Exposes an optional `client` kwarg for a `dask.distributed.Client`
- Attempts to repeat chunking heuristic from `budget` for a `client`

2025-01-06 09:36 UTC, sjperkins commented
There are some merge conflicts from #70. Could you please merge/rebase this branch on top of master?

2025-01-06 15:16 UTC, sjperkins requested changes
Thanks for putting this together @AlecThomson.

I think it would be good to expose some commandline arguments that enable the distributed compute functionality.

Using a smaller subset of what's available in Quartical's CLI would be useful:

- https://github.com/ratt-ru/QuartiCal/blob/eeffcab893844069005af5b00c2bc64d7bfbceca/quartical/config/argument_schema.yaml#L401-L425
- https://github.com/ratt-ru/QuartiCal/blob/eeffcab893844069005af5b00c2bc64d7bfbceca/quartical/executor.py#L67-L104

Following the above template, how about?

- a `--scheduler` option which can take a choice of `["threads", "distributed"]`
- if "scheduler" is "distributed", then the value of  an `--address` argument can be used to construct a `Client`. Otherwise the contents of the  DASK_SCHEDULER_ADDRESS  environment variable can be used as in Quartical's logic.
- Quartical's `--threads` probably corresponds to crystalball's `--nworkers`. The name probably shouldn't be changed, even if consistency is desirable. However, if the scheduler is "threads", the `--nworkers` should be used to set the size of the thread pool.

Also, there appears to be duplication in both the Client and standard versions of the budgeting code. Would it be possible to split out the querying of system parameters into separate functions while consolidating budgeting into a single function?

2025-01-06 15:16 UTC, sjperkins commented on pyproject.toml
> +dask = "*"
The dask dependency can be removed, as `dask-ms` will set this appropriately.

2025-01-07 05:08 UTC, AlecThomson commented
Ok @sjperkins I've had a crack at these changes. Let me know what you think.

2025-01-09 08:03 UTC, sjperkins approved these changes

2025-01-09 08:03 UTC, merged

2025-01-09 08:03 UTC, sjperkins commented
Thank for the contribution @AlecThomson.